// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB17cl21TVFRU2TVTKxym3fmGLo6vTWwfc',
    appId: '1:104474286965:web:88e73ba1e45abb3eb8913c',
    messagingSenderId: '104474286965',
    projectId: 'amplify-1da38',
    authDomain: 'amplify-1da38.firebaseapp.com',
    storageBucket: 'amplify-1da38.appspot.com',
    measurementId: 'G-99353WSGWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaB66f0fqSUnae7vcKXlCj9zrttM2ZxpU',
    appId: '1:104474286965:android:cf9697c24da7049cb8913c',
    messagingSenderId: '104474286965',
    projectId: 'amplify-1da38',
    storageBucket: 'amplify-1da38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSEetSxMtxYPo_rVOMnJ3u1iOwq30fG2Y',
    appId: '1:104474286965:ios:2990912d77a8cb60b8913c',
    messagingSenderId: '104474286965',
    projectId: 'amplify-1da38',
    storageBucket: 'amplify-1da38.appspot.com',
    iosClientId: '104474286965-0le0nri355q2n0r9hr5ql6tgl941mlk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSEetSxMtxYPo_rVOMnJ3u1iOwq30fG2Y',
    appId: '1:104474286965:ios:2990912d77a8cb60b8913c',
    messagingSenderId: '104474286965',
    projectId: 'amplify-1da38',
    storageBucket: 'amplify-1da38.appspot.com',
    iosClientId: '104474286965-0le0nri355q2n0r9hr5ql6tgl941mlk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB17cl21TVFRU2TVTKxym3fmGLo6vTWwfc',
    appId: '1:104474286965:web:d289c89cb985eea5b8913c',
    messagingSenderId: '104474286965',
    projectId: 'amplify-1da38',
    authDomain: 'amplify-1da38.firebaseapp.com',
    storageBucket: 'amplify-1da38.appspot.com',
    measurementId: 'G-XCNMRRQ3RM',
  );

}